# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoptions', '0005_delete_arrestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField()),
                ('PK', models.TextField()),
                ('CCR', models.TextField()),
                ('AGE', models.TextField()),
                ('GENDER', models.TextField()),
                ('RACE', models.TextField()),
                ('ARRESTTIME', models.TextField()),
                ('ARRESTLOCATION', models.TextField()),
                ('OFFENSES', models.TextField()),
                ('INCIDENTLOCATION', models.TextField()),
                ('INCIDENTNEIGHBORHOOD', models.TextField()),
                ('INCIDENTZONE', models.TextField()),
                ('INCIDENTTRACT', models.TextField()),
                ('COUNCIL_DISTRICT', models.TextField()),
                ('PUBLIC_WORKS_DIVISION', models.TextField()),
                ('X', models.TextField()),
                ('Y', models.TextField()),
            ],
        ),
    ]
